//
// Created by barak on 04/05/2020.
//

#ifndef AILABGENETICALGORITHM_NQUEENS_CONSTS_H
#define AILABGENETICALGORITHM_NQUEENS_CONSTS_H

static const int DEFAULT_NUMBER_OF_QUEENS_AND_BOARD_SIZE = 12;

#endif //AILABGENETICALGORITHM_NQUEENS_CONSTS_H
