//
// Created by barak on 13/06/2020.
//

#ifndef AILABGENETICALGORITHM_CONSTS_H
#define AILABGENETICALGORITHM_CONSTS_H

static const int MAX_PARSE_TREE_DEPTH = 2;
#endif //AILABGENETICALGORITHM_CONSTS_H
