//
// Created by barak on 22/06/2020.
//

#ifndef AILABGENETICALGORITHM_INITIALIZATIONMETHOD_H
#define AILABGENETICALGORITHM_INITIALIZATIONMETHOD_H

enum InitializationMethod{
    Grow,
    Full
};
#endif //AILABGENETICALGORITHM_INITIALIZATIONMETHOD_H
