//
// Created by barak on 24/05/2020.
//

#ifndef AILABGENETICALGORITHM_KNAPSACKGENETICSTRUCT_H
#define AILABGENETICALGORITHM_KNAPSACKGENETICSTRUCT_H

#endif //AILABGENETICALGORITHM_KNAPSACKGENETICSTRUCT_H
