//
// Created by barak on 09/05/2020.
//

#ifndef AILABGENETICALGORITHM_RANDOM_COLLECTOR_GENERATOR_H
#define AILABGENETICALGORITHM_RANDOM_COLLECTOR_GENERATOR_H


class random_collector_generator {

};


#endif //AILABGENETICALGORITHM_RANDOM_COLLECTOR_GENERATOR_H
