//
// Created by barak on 30/04/2020.
//

#ifndef AILABGENETICALGORITHM_GENETICSTRINGMATCHER_H
#define AILABGENETICALGORITHM_GENETICSTRINGMATCHER_H

class GeneticStringMatcher {
public:
    GeneticStringMatcher();
};


#endif //AILABGENETICALGORITHM_GENETICSTRINGMATCHER_H
