//
// Created by barak on 27/06/2020.
//

#ifndef AILABGENETICALGORITHM_PARALLELIZEDSTRINGMATCHING_H
#define AILABGENETICALGORITHM_PARALLELIZEDSTRINGMATCHING_H



class ParallelizedStringMatching {

};



#endif //AILABGENETICALGORITHM_PARALLELIZEDSTRINGMATCHING_H
