//
// Created by barak on 05/05/2020.
//

#ifndef AILABGENETICALGORITHM_GENERICGENETICALGORITHMSOLVER_H
#define AILABGENETICALGORITHM_GENERICGENETICALGORITHMSOLVER_H


class GenericGeneticAlgorithmSolver {

};


#endif //AILABGENETICALGORITHM_GENERICGENETICALGORITHMSOLVER_H
