//
// Created by barak on 09/05/2020.
//

#ifndef AILABGENETICALGORITHM_MUTATIONOPERATORS_H
#define AILABGENETICALGORITHM_MUTATIONOPERATORS_H
enum MutationOperator{
    Exchange,
    Inversion
};
#endif //AILABGENETICALGORITHM_MUTATIONOPERATORS_H
