//
// Created by barak on 27/06/2020.
//

#ifndef AILABGENETICALGORITHM_PARALLELIZEDGENETICSOLVER_H
#define AILABGENETICALGORITHM_PARALLELIZEDGENETICSOLVER_H

#endif //AILABGENETICALGORITHM_PARALLELIZEDGENETICSOLVER_H
